server:
  port: 8080

spring:
  application:
    name: spend-tracker

  security: #TODO: KEYS MUST BE CHANGED BEFORE USE
    jwt: #HS512
      secret: M6Frc4ucnWmqM0LoPKruoWX6W8auInGSx66BFVhHGPqtlfxB5tkseU/mPD0jttEBv9LL7xN7qqoaHY5yNc+TVA==
      jwt-expiration: 3600000 #1h
      refresh-expiration: 2592000000 #30d
    aes: #AES256
      key: 1umX42v0qxUm9db0Mwjli6r+cNZ6UsqcLL3r+cQF9+Y=


  datasource:
    url: jdbc:postgresql://localhost:5432/spendtracker
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true